name: Build second after slow

on:
  workflow_run:
    workflows: [Build slow]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: cat text file
        run: cat fred.txt