name: Build slow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for 50 minutes
        run: sleep 3000

      - name: create text file
        run: echo "fred was here" > fred.txt