name: Build on Pull Request

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the username
        run: echo "The username is ${{ github.event.pull_request.user.login }}"
      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.pull_request.user.login }} > ./pr/UN
          - uses: actions/upload-artifact@v2
            with:
              name: pr
              path: pr/